# require the branch name to be master (note for PRs this is the base branch name)
if: branch = master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  on:
    branch: master
  local_dir: docs
  repo: openziti.github.io
  committer_from_gh: ziti-ci