dist: bionic

services:
  - docker

before_script:
  - docker pull openziti/doc:docfx

script:
  - >
    docker run --rm -it -v $(pwd):/doc -e AWS_ACCESS_KEY_ID=$aws_access_key_id
    -e AWS_SECRET_ACCESS_KEY=$aws_secret_access_key
    -e AWS_DEFAULT_REGION=us-east-1
    openziti/doc:latest
    /bin/sh -c "/doc/publish.sh"

