# require the branch name to be master (note for PRs this is the base branch name)
if: branch = master

dotnet: 3.0.0

#mono:
#  - latest

script:
  - ls -l
  - export GIT_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - ./publish.sh docs
