language: csharp

mono: latest

before_install:
  - export PATH=$(pwd):$PATH
  - nuget install docfx.console -ExcludeVersion
  - echo "mono docfx.console/tools/docfx.exe" > docfx
  - docfx --version
  - apt install python-pip
  - pip install -U pip
  - pip install awscli
  - ./prepare-ci.sh

script:
  - ./publish.sh

